#!/usr/bin/python -B

"""
SpotifyServer

HTTP server wrapper around Spotify.

Copyright (c) 2014 All Right Reserved, Liam Wickins

Please see the LICENSE file for more information.

THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.
"""

from __future__ import division
from __future__ import print_function
import sys, time, readline, os, threading, codecs
from optparse import OptionParser
from MusicDB import MusicDB
from SpotifyService import SpotifyService
from MusicOutcome import MusicOutcome
from SpotifySearch import SpotifySearch
from PlayQueue import PlayQueue
from PulseAudio import PulseAudio
from MusicMessage import *
import json, spotify
import BaseHTTPServer, SimpleHTTPServer

parser = OptionParser()
parser.add_option("-u", "--user", dest="user",
                  help="Spotify user name",
                  action="store", type="string")
parser.add_option("-p", "--pass", dest="password",
                  help="Spotify password",
                  action="store", type="string")
parser.add_option("-q", "--quiet", dest="announce",
                  help="Synthesizer announcements are suppressed",
                  action="store_false", default=True)
parser.add_option("-d", "--db", dest="musicDatabase",
                  help="Music database",
                  action="store", type="string")
parser.add_option("-r", "--port", dest="port",
                  help="Server port number",
                  action="store", default=8000, type="int")
parser.add_option("-s", "--addr", dest="addr",
                  help="Server IP address",
                  action="store", default="127.0.0.1", type="string")
parser.add_option("-o", "--root", dest="root",
                  help="HTTP server root directory",
                  action="store", default="html", type="string")
(options, args) = parser.parse_args()

# Required for E-Speak python module
if (options.announce):

  sys.path.append("../espeak.py")
  from TextToSpeech import TextToSpeech

  # Create speech synthesizer
  synth = TextToSpeech()

if (not options.user or not options.password):
  print("You must have a Spotify account and token to use this program.")
  exit()

# Create client session and login
m = SpotifyService()
if (m.LoginUser(options.user, options.password) != 0):
  m.Exit()
  exit("Error: Failed to login to Spotify")

# Create pulse audio session
pa = PulseAudio()

# Create offline music database connection
if (options.musicDatabase):
  db = MusicDB(options.musicDatabase)
else:
  db = None

trackCount = 0
lastTrackCount = 0
def NewTrackIndication():
  global trackCount
  trackCount += 1

# Create play queue
pq = PlayQueue(m, NewTrackIndication)

def Debug(*objs):
  print("DEBUG: ", *objs, file=sys.stderr)

def UnicodeToAscii(u):
  table = { 0x2018:0x27, 0x2019:0x27, 0x201C:0x22, 0x201D:0x22 }
  return u.translate(table).encode('ascii', 'ignore')

# Helper function to expand all elements starting from track URI
def ExpandTrackInfo(session, uri):
  if (uri is None):
    return None
  track = session.GetTrackInfo(spotify.Track(uri).load())
  track['artists'] = [session.GetArtistInfo(a)['name'] for a in track['artists']]
  track['album'] =  session.GetAlbumInfo(track['album'])['name']
  track['link'] = track['link'].uri
  track.pop('playable',None)
  return track

def LoadAlbumImg(uri):
  track = spotify.Track(uri).load()
  image = track.album.load().cover()
  if (image):
    return image.load().data_uri
  return None

def LoadArtistImg(uri):
  track = spotify.Track(uri).load()
  image = track.artists[0].load().portrait()
  if (image):
    return image.load().data_uri
  return None

# Helper function to announce/show current track information
def TrackInfo():
  t = pq.GetCurrentTrack()
  if (t):
    track = ExpandTrackInfo(m, t)
    text = UnicodeToAscii("Track : " + track['name'] + "; Album : " + track['album'] + "; Artist : " + track['artists'][0])
    if (options.announce):
      synth.SpeakAndWaitUntilFinished(text)

def ProcessOutcome(outcome):

  msg = MusicMessage()

  # Try to gather outcome information from the command
  if (outcome):
    intent = outcome.intent.name
    entities = outcome.entities
  else:
    msg.AddStatus(MusicStatus.STATUS_INTENT_NOT_SUPPORTED)
    intent = 'Uknown'
    entities = None
  if intent == 'play' and not entities:
    pq.Play()
    TrackInfo()
    NewTrackIndication()
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'stop':
    pq.Stop()
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'shuffle':
    state = outcome.GetEntity('state', None)
    if (state):
      pq.Shuffle(state)
    else:
      state = pq.GetShuffleState()
    msg.AddStatus(MusicStatus.STATUS_OK)
    msg += {'shuffle': state}
  elif intent == 'skip':
    number = int(outcome.GetEntity('number', 1))
    pq.SkipForward(number)
    TrackInfo()
    NewTrackIndication()
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'back':
    number = int(outcome.GetEntity('number', 1))
    pq.SkipBack(number)
    TrackInfo()
    NewTrackIndication()
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif ((intent == 'search' or intent == 'play' or intent == 'find' or intent == 'insert' or
         intent == 'append') and entities):
    try:
      q = SpotifySearch(entities, m, musicDb=db, offline=False)
      results = q.GetQueryResults()
    except:
      msg.AddStatus(MusicStatus.STATUS_BAD_SEARCH_QUERY_EXCEPTION)
      results = []
    numTracks = len(results)
    msg.AddStatus(MusicStatus.STATUS_OK)
    msg += {'numTracks': numTracks}
    if (intent == 'play' and numTracks > 0):
      pq.Insert(results)
      pq.ResetPos()
      pq.Play()
      TrackInfo()
      NewTrackIndication()
    elif (numTracks > 0 and intent == 'insert'):
      pq.Insert(results)
    elif (numTracks > 0):
      pq.Append(results)
  elif intent == 'reset':
    pos = int(outcome.GetEntity('position', 0))
    pq.ResetPos(pos)
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'pause':
    pq.Pause()
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'resume':
    pq.Resume()
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'clear':
    pq.Clear()
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'mute':
    sink = pa.GetDefaultSink()
    pa.MuteSink(sink)
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'unmute':
    sink = pa.GetDefaultSink()
    pa.UnuteSink(sink)
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'volume':
    volume = outcome.GetEntity('volume')
    sink = pa.GetDefaultSink()
    if (volume):
      pa.SetSinkVolume(sink, int(volume))
    curVol = pa.GetSinkVolume(sink)
    msg += {'volume':curVol[0]}
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'sink':
    index = outcome.GetEntity('sink')
    if (index):
      sink = pa.GetSink(index)
      pa.SetDefaultSink(sink)
    else:
      sinks = pa.GetSinks()
      msg += {'sinks': sinks, 'hash':pa.ComputeHash(sinks)}
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'louder':
    sink = pa.GetDefaultSink()
    vol = pa.GetSinkVolume(sink)[0] + 10
    if (vol > 100): vol = 100
    pa.SetSinkVolume(sink, vol)
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'quieter':
    sink = pa.GetDefaultSink()
    vol = pa.GetSinkVolume(sink)[0] - 10
    if (vol < 0): vol = 0
    pa.SetSinkVolume(sink, vol)
    msg.AddStatus(MusicStatus.STATUS_OK)
  elif intent == 'image':
    uri = outcome.GetEntity('uri')
    if (uri):
      album = LoadAlbumImg(uri)
      artist = LoadArtistImg(uri)
      msg.AddStatus(MusicStatus.STATUS_OK)
      msg += {'albumImage':album, 'artistImage':artist}
  elif intent == 'info':
    obj = outcome.GetEntity('object')
    if (obj):
      status = MusicStatus.STATUS_OK
      if (obj == 'playlist'):
        msg += {'playlist':[ExpandTrackInfo(m, i) for i in pq.GetAllTracks()]}
      elif (obj == 'track'):
        msg += {'track':ExpandTrackInfo(m, pq.GetCurrentTrack()),'playlistPosition':pq.QueueIndex(), 'state':m.GetPlayState()}
      elif (obj == 'playlisthash'):
        msg += {'playlisthash':pq.GetPlaylistHash()}
      else:
        status = MusicStatus.STATUS_UNKNOWN_INFO_OBJECT_REQUESTED
      msg.AddStatus(status)
    else:
      msg.AddStatus(MusicStatus.STATUS_OK)
      msg += {'playlist':[ExpandTrackInfo(m, i) for i in pq.GetAllTracks()]}
      msg += {'track':ExpandTrackInfo(m, pq.GetCurrentTrack())}
  elif intent == 'stats':
    stats = m.GetStatistics()
    msg.AddStatus(MusicStatus.STATUS_OK)
    msg += {'stats': {'occupancy':stats[0], 'drops':stats[1], 'percent':stats[2], 'total':stats[3], 'rate':stats[4]}}

  return msg

# HTTP server
class MusicHTTPServer(BaseHTTPServer.HTTPServer):

  def __init__(self, addr, requestHandlerClass, documentRoot=None):
 
    # See SocketServer.TCPServer.__init__
    BaseHTTPServer.HTTPServer.__init__(self, addr, requestHandlerClass)
    if (documentRoot):
      os.chdir(documentRoot)

class MusicHTTPHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):

  def do_OPTIONS(self):
    self.send_response(200)
    self.send_header('Access-Control-Allow-Origin', '*')
    self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
    self.send_header("Access-Control-Allow-Headers", "X-Requested-With, Content-Type, Content-Length") 

  def do_POST(self):
    self.send_response(200)
    self.send_header('Access-Control-Allow-Origin', '*')
    self.send_header('Content-Type', 'application/json')
    self.end_headers()
    data = self.rfile.read(int(self.headers.get('content-length', 0)))
    try:
      command = json.loads(data)
      outcome = MusicOutcome(command['command'])
    except:
      outcome = None
    resp = ProcessOutcome(outcome)
    self.wfile.write(resp)

print("HTTPD running...")
addr = ('', options.port)
httpd = MusicHTTPServer(addr, MusicHTTPHandler, documentRoot=options.root)
httpd.serve_forever()

# Logout and delete session
m.LogoutUser()
m.Exit()
